### ISSUE TITLE
redis traffic analysis error

### ISSUE THREAD

**Issue by y123456yz** [hirose31/redis-traffic-stats#5]
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
Use of uninitialized value $_[0] in substr at script/redis-traffic-stats line 303.
substr outside of string at script/redis-traffic-stats line 303.
Use of uninitialized value $line in concatenation (.) or string at script/redis-traffic-stats line 335.
Cannot parse:  at script/redis-traffic-stats line 335.

thanks

**Comment by hirose31** [comment]
Could you please tell me how to reproduce?

**Comment by hirose31** [comment]
no response for a long time
